version: 2.1

orbs:
  ruby: circleci/ruby@0.2.1

jobs:
  test:
    executor:
      name: ruby/default
      tag: '2.7.0'
    steps:
      - checkout
      - ruby/load-cache:
      - ruby/install-deps
      - ruby/save-cache:
      - ruby/run-tests

workflows:
  version: 2
  test:
    jobs:
      - test
